import pyautogui,time
pyautogui.keyDown('alt')
time.sleep(.01)
pyautogui.press('tab')
time.sleep(.01)
pyautogui.keyUp('alt')
time.sleep(.01)
pyautogui.click(1100,70)
time.sleep(11)
pyautogui.click(160,220)
time.sleep(.01)
pyautogui.press('tab')
time.sleep(.01)
pyautogui.write('96')
for i in range(10):
	time.sleep(.01)
	pyautogui.press('tab')
pyautogui.write('T')
time.sleep(.01)
pyautogui.press('tab')
pyautogui.press('tab')
time.sleep(.01)
pyautogui.hotkey('ctrl', 'a')
pyautogui.write('www.gprsmodem.uz')
time.sleep(.01)
pyautogui.press('tab')
time.sleep(.01)
pyautogui.hotkey('ctrl', 'a')
pyautogui.write('7778')
for i in range(6):
	time.sleep(.01)
	pyautogui.press('tab')
pyautogui.write('L')
time.sleep(.01)
pyautogui.press('tab')
time.sleep(.01)
pyautogui.press('space')
for i in range(6):
	time.sleep(.01)
	pyautogui.press('tab')
time.sleep(.01)
pyautogui.press('space')
time.sleep(.01)
pyautogui.press('enter')
for i in range(9):
	time.sleep(.01)
	pyautogui.press('tab')
pyautogui.press('pagedown')
pyautogui.press('tab')
pyautogui.hotkey('ctrl', 'a')
pyautogui.write('BlueStar')
pyautogui.press('tab')
pyautogui.hotkey('ctrl', 'a')
pyautogui.write('BlueStar')
pyautogui.press('tab')
pyautogui.hotkey('ctrl', 'a')
pyautogui.write('internet')
pyautogui.press('tab')
pyautogui.hotkey('ctrl', 'a')
pyautogui.write('internet')
pyautogui.press('tab')
pyautogui.hotkey('ctrl', 'a')
pyautogui.write('internet')
pyautogui.hotkey('pageup')
pyautogui.doubleClick(200,610)
time.sleep(.5)
pyautogui.hotkey('ctrl','c')
time.sleep(.5)
pyautogui.click(1200,60)
pyautogui.press('tab')
pyautogui.press('tab')
#pyautogui.press('enter')
pyautogui.alert(text='Nomerini yozib ol va  ВСТАВИТЬ qil WORDGA', title='OGOHLANTIRISH', button='OK')
